Repository hypothesis/lms, pull requests merged in 2020-02, with the labels that each got.

#1412 Set Via 3 as the default for development
  README.markdown
  conf/development.ini
Labels: Technical enabler

#1395 Add an initial set of frontend a11y tests using axe-core
  gulpfile.js
  lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
  lms/static/scripts/frontend_apps/components/test/Dialog-test.js
  lms/static/scripts/frontend_apps/components/test/ErrorDisplay-test.js
  lms/static/scripts/frontend_apps/components/test/FileList-test.js
  lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
  lms/static/scripts/frontend_apps/components/test/LMSGrader-test.js
  lms/static/scripts/frontend_apps/components/test/StudentSelector-test.js
  lms/static/scripts/frontend_apps/components/test/SubmitGradeForm-test.js
  lms/static/scripts/frontend_apps/components/test/SvgIcon-test.js
  lms/static/scripts/frontend_apps/components/test/Table-test.js
  lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
  lms/static/scripts/frontend_apps/components/test/ValidationMessage-test.js
  lms/static/scripts/karma.config.js
  lms/static/scripts/test-util/accessibility.js
  package.json
  yarn.lock
Labels: Accessibility

#1438 Revert "Bump webargs from 5.5.2 to 5.5.3"
  requirements.txt
  tests/unit/conftest.py
  tests/unit/lms/validation/authentication/_oauth_test.py
Labels: Bug

#1445 Add front-end formatting to the format command
  Makefile
Labels: Tech debt

#1436 Move rpc_server_config into js_config
  lms/resources/_lti_launch.py
  lms/static/scripts/postmessage_json_rpc/server/server-test.js
  lms/static/scripts/postmessage_json_rpc/server/server.js
  lms/templates/base.html.jinja2
  tests/unit/lms/resources/_lti_launch_test.py
Labels: Tech debt

#1437 Add a convenient `make sure` command
  Makefile
Labels: Technical enabler

#1447 Specify query string as the place to look for the Canvas OAuth schema
  lms/validation/authentication/_oauth.py
Labels: Added to sprint, Tech debt

#1456 Remove the Via 2 feature flag
  lms/views/helpers/_via.py
  tests/unit/lms/views/helpers/_via_test.py
Labels: Tech debt

#1515 Remove un-used test imports
  tests/bdd/steps/lms_db.py
  tests/unit/lms/resources/_js_config_test.py
  tests/unit/lms/resources/lti_launch_test.py
  tests/unit/lms/services/lti_outcomes_test.py
  tests/unit/lms/views/api/canvas/authorize_test.py
  tests/unit/lms/views/api/canvas/files_test.py
  tests/unit/lms/views/api/lti_test.py
Labels: Tech debt
