Repository hypothesis/lms, pull requests merged in 2021-07, with the labels that each got.

#2914 Ignore anything but minor updates for Python docker images
  .github/dependabot.yml
Labels: Tech debt

#2938 Reduce repetition in the application instance admin pages
  lms/templates/admin/instance.html.jinja2
  lms/views/admin.py
  tests/unit/lms/views/admin_test.py
Labels: OneDrive, Tech debt

#2937 Add Microsoft OneDrive backend settings
  lms/config/__init__.py
  lms/resources/_js_config/__init__.py
  lms/resources/_js_config/file_picker_config.py
  lms/templates/admin/instance.html.jinja2
  lms/views/admin.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/resources/_js_config/file_picker_config_test.py
  tests/unit/lms/views/admin_test.py
  tox.ini
Labels: OneDrive, enhancement

#2939 Use the setting and sub-setting name to generate the form field name
  lms/templates/admin/instance.html.jinja2
  lms/views/admin.py
  tests/unit/lms/views/admin_test.py
Labels: Tech debt

#2975 Add product metadata to the `pyproject.toml` file
  pyproject.toml
Labels: enhancement

#2912 Rename ModuleItemConfiguration to Assignment
  bin/update_dev_data.py
  lms/models/__init__.py
  lms/models/assignment.py
  lms/routes.py
  lms/services/assignment.py
  lms/services/canvas.py
  lms/static/scripts/frontend_apps/components/FilePickerFormFields.js
  lms/validation/__init__.py
  lms/validation/_assignment.py
  lms/views/api/canvas/files.py
  lms/views/basic_lti_launch.py
  lms/views/predicates/_lti_launch.py
  tests/bdd/steps/feature_steps/lms.feature
  tests/factories/__init__.py
  tests/factories/assignment.py
  tests/functional/api/basic_lti_launch_test.py
  tests/unit/conftest.py
  tests/unit/lms/models/assignment_test.py
  tests/unit/lms/models/module_item_configuration_test.py
  tests/unit/lms/services/assignment_test.py
  tests/unit/lms/services/canvas_test.py
  tests/unit/lms/validation/_assignment_test.py
  tests/unit/lms/views/api/canvas/files_test.py
  tests/unit/lms/views/basic_lti_launch_test.py
  tests/unit/lms/views/predicates/_lti_launch_test.py
Labels: Backend
