Repository hypothesis/lms, pull requests merged in 2022-04, with the labels that each got.

#3871 Add support for `reportActivity` method
  lms/static/scripts/frontend_apps/services/client-rpc.js
  lms/static/scripts/frontend_apps/services/test/client-rpc-test.js
  lms/static/scripts/postmessage_json_rpc/server.js
  lms/static/scripts/postmessage_json_rpc/test/server-test.js
Labels: Frontend

#3877 Expose `submitted_at` in canvas grading API
  lms/validation/_api.py
  lms/views/api/lti.py
  tests/unit/lms/views/api/lti_test.py
Labels: Technical enabler

#3892 Refactor grading service V11 tests main fixture
  tests/unit/lms/services/lti_grading/_v11_test.py
Labels: Tech debt

#3887 Refactor grading service V11 tests
  tests/unit/lms/services/lti_grading/_v11_test.py
Labels: Tech debt

#3893 Conditionally submit empty grading submission after activity, if configured as such
  lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
  lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
  lms/static/scripts/frontend_apps/config.js
  lms/static/scripts/frontend_apps/services/client-rpc.js
Labels: Frontend
