Repository hypothesis/lms, pull requests merged in 2022-07, with the labels that each got.

#4152 Parameterize auth urls
  lms/product/blackboard/product.py
  lms/product/canvas/product.py
  lms/product/product.py
  lms/resources/_js_config/__init__.py
  lms/resources/_js_config/file_picker_config.py
  lms/views/api/blackboard/files.py
  lms/views/api/exceptions.py
  tests/unit/conftest.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/resources/lti_launch_test.py
  tests/unit/lms/views/api/exceptions_test.py
Labels: enhancement

#4181 Fix route instantiation for Canvas and Blackboard
  lms/product/blackboard/product.py
  lms/product/canvas/product.py
Labels: Bug

#4170 Don't send the unnecessary nonce value in LTIA service
  lms/services/ltia_http.py
  lms/views/lti/deep_linking.py
  tests/unit/lms/services/ltia_http_test.py
  tests/unit/lms/views/lti/deep_linking_test.py
Labels: Bug

#4173 Use pyramid services as the initialisation mechanism
  lms/product/__init__.py
  lms/product/blackboard/__init__.py
  lms/product/blackboard/_plugin/grouping.py
  lms/product/canvas/__init__.py
  lms/product/canvas/_plugin/grouping.py
  lms/product/plugin/__init__.py
  lms/product/plugin/grouping_service.py
  lms/product/plugin/plugin.py
  lms/product/product.py
  lms/services/grouping/service.py
  tests/unit/conftest.py
  tests/unit/lms/product/blackboard/_plugin/grouping_test.py
  tests/unit/lms/product/canvas/_plugin/grouping_test.py
  tests/unit/lms/product/plugin/__init__.py
  tests/unit/lms/product/plugin/test_plugin.py
  tests/unit/lms/product/product_test.py
  tests/unit/lms/services/grouping/factory_test.py
  tests/unit/lms/services/grouping/service_test.py
Labels: Tech debt

#4213 Ignore leading and trailing space in JSTOR input field
  lms/static/scripts/frontend_apps/utils/jstor.js
  lms/static/scripts/frontend_apps/utils/test/jstor-test.js
Labels: JSTOR

#4186 Remove `is_canvas` in favour of `product.family`
  lms/resources/lti_launch.py
  lms/views/lti/basic_launch.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/resources/_js_config/file_picker_config_test.py
  tests/unit/lms/resources/lti_launch_test.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: Tech debt

#4182 Accept assignment id instead of just assignment for `upsert_assignment_groupings`
  lms/services/assignment.py
  lms/views/api/sync.py
  lms/views/lti/basic_launch.py
  tests/unit/lms/services/assignment_test.py
  tests/unit/lms/views/api/sync_test.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: Tech debt

#4260 Use a service method to decide if `VitalSource` is available
  lms/resources/_js_config/__init__.py
  lms/resources/_js_config/file_picker_config.py
  lms/services/vitalsource/factory.py
  lms/services/vitalsource/service.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/resources/_js_config/file_picker_config_test.py
  tests/unit/lms/services/vitalsource/factory_test.py
  tests/unit/lms/services/vitalsource/service_test.py
Labels: Tech debt, Bug

#4241 Nest in the H connection details to leave space for possible LMS ones in future
  bin/gateway/config/h_calls_dev.json
  bin/gateway/config/h_calls_prod.json
  bin/gateway/config/h_calls_qa.json
  bin/gateway/h_call.py
  docs/gateway/schema.json
  lms/views/api/gateway.py
  tests/functional/api/gateway_test.py
  tests/unit/lms/views/api/gateway_test.py
Labels: Tech debt

#4262 Add per-instance VitalSource API keys and user ID field settings
  lms/templates/admin/instance.html.jinja2
  lms/views/admin/application_instance.py
Labels: Technical enabler

#4267 Fix functional/bdd test H-API mocks
  tests/bdd/steps/h_api.py
  tests/conftest.py
  tests/functional/api/gateway_test.py
  tests/functional/conftest.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/services/grant_token_test.py
  tests/unit/lms/services/h_api_test.py
Labels: Bug

#4265 Sync the user before we issue credentials in the Gateway
  bin/gateway/config/gateway_qa_example.json
  docs/gateway/02_api_spec.md
  lms/views/api/gateway.py
  tests/functional/api/gateway_test.py
  tests/unit/lms/views/api/gateway_test.py
Labels: Bug
