Repository hypothesis/lms, pull requests merged in 2022-08, with the labels that each got.

#4289 Add basic test for LMS frontend entry point
  lms/static/scripts/frontend_apps/index.js
  lms/static/scripts/frontend_apps/test/index-test.js
  rollup-tests.config.mjs
Labels: Frontend

#4297 Add details of JSTOR linked items and containing journal / book title
  lms/services/jstor/_article_metadata.py
  tests/unit/lms/services/jstor/_article_metadata_test.py
Labels: enhancement

#4306 Rollback failed transaction in admin pages
  lms/views/admin/application_instance.py
  tests/unit/lms/views/admin/application_instance_test.py
Labels: Bug

#4319 Remove unused `containerTitle` field
  lms/static/scripts/frontend_apps/services/client-rpc.js
  lms/static/scripts/frontend_apps/services/content-info-fetcher.js
  lms/static/scripts/frontend_apps/services/test/content-info-fetcher-test.js
Labels: Frontend

#4270 Move the call to get the SSO link to the front end as a call back
  lms/resources/_js_config/__init__.py
  lms/routes.py
  lms/views/api/vitalsource.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/views/api/vitalsource_test.py
Labels: enhancement

#4305 Capture `ExternalRequestErrors` for 404's in VitalSource instead of raising them
  lms/services/vitalsource/_client.py
  tests/unit/lms/services/vitalsource/_client_test.py
Labels: Bug

#4354 Backfill events from `lti_launches`
  lms/migrations/versions/396f46318023_events_backfill.py
Labels: Technical enabler

#4320 Newer Canvas instances will now return a nice error for unavailable files
  lms/services/exceptions.py
  tests/unit/lms/services/exceptions_test.py
Labels: Bug

#4371 Add a work around to disable licence checking for VS SSO
  lms/services/vitalsource/factory.py
  lms/services/vitalsource/service.py
  lms/templates/admin/instance.html.jinja2
  lms/views/admin/application_instance.py
  tests/unit/lms/services/vitalsource/factory_test.py
  tests/unit/lms/services/vitalsource/service_test.py
Labels: Bug

#4373 Fix roles reported for LTI1.3 launches
  lms/models/lti_params.py
  tests/unit/lms/models/lti_params_test.py
Labels: Bug
