Repository hypothesis/lms, pull requests merged in 2022-06, with the labels that each got.

#3996 Migration for renaming `module_item_configurations` to `assignment`
  lms/migrations/versions/bdfe1c72813f_rename_module_item_configurations_to_assignment.py
Labels: Tech debt, Technical enabler

#4019 Change references to `module_item_configuration` to `assignment`
  lms/models/assignment.py
  lms/views/lti/deep_linking.py
Labels: Tech debt

#4023 Refactor the `AssignmentService` tests to use fixtures
  tests/unit/lms/services/assignment_test.py
Labels: Tech debt

#4030 Re-order the views to have common ones at the top
  lms/views/lti/basic_launch.py
Labels: Tech debt

#4029 Refactor LTI launch tests to remove caller pattern and make them easier to maintain
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: Tech debt

#4027 Add useFetch hook to make managing API fetches in components easier
  lms/static/scripts/frontend_apps/utils/fetch.js
  lms/static/scripts/frontend_apps/utils/test/fetch-test.js
Labels: Frontend

#4024 Rename the assignment service methods to have `assignment` in them
  lms/resources/lti_launch.py
  lms/services/assignment.py
  lms/views/api/blackboard/sync.py
  lms/views/api/canvas/files.py
  lms/views/lti/basic_launch.py
  lms/views/predicates/_lti_launch.py
  tests/unit/lms/resources/lti_launch_test.py
  tests/unit/lms/services/assignment_test.py
  tests/unit/lms/views/api/blackboard/sync_test.py
  tests/unit/lms/views/api/canvas/files_test.py
  tests/unit/lms/views/lti/basic_launch_test.py
  tests/unit/lms/views/predicates/_lti_launch_test.py
Labels: Tech debt, Technical enabler

#4040 Refactor the LTI 1.3 func tests to not rely on JS config on the error page
  tests/functional/lti_certification/v13/assertions.py
  tests/functional/lti_certification/v13/conftest.py
  tests/functional/lti_certification/v13/core/test_valid_student_launches.py
  tests/functional/lti_certification/v13/core/test_valid_teacher_launches.py
Labels: Technical enabler

#4039 Add `useAPIFetch` hook to simplify API fetches
  lms/static/scripts/frontend_apps/utils/api.js
  lms/static/scripts/frontend_apps/utils/test/api-test.js
Labels: Frontend

#4041 Use `lti_params` for 1.3 compatibility in the LTI launches
  lms/views/lti/basic_launch.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: Bug

#4032 Upsert data about assignments on every launch
  lms/views/lti/basic_launch.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: enhancement

#4026 Add article metadata and thumbnail to JSTOR picker
  lms/static/scripts/frontend_apps/components/JSTORPicker.js
  lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
  lms/static/scripts/frontend_apps/utils/jstor.js
  lms/static/scripts/frontend_apps/utils/test/jstor-test.js
Labels: Frontend, Backend

#4059 Add a migration for the new assignment columns
  lms/migrations/versions/83ec5ef85d44_add_more_metadata_to_the_assignment.py
Labels: Technical enabler

#4056 Store more metadata with assignments
  lms/models/assignment.py
  lms/models/lti_params.py
  lms/services/assignment.py
  lms/views/lti/basic_launch.py
  tests/unit/conftest.py
  tests/unit/lms/models/lti_params_test.py
  tests/unit/lms/services/assignment_test.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: enhancement

#4064 DB migration for LTI roles and assignment membership tables
  lms/migrations/versions/fe80746cf145_add_lti_roles_and_assignment_membership.py
Labels: Technical enabler

#4067 DB migration for `assignment_grouping`
  lms/migrations/versions/1e146996cca6_add_assignment_grouping.py
Labels: Technical enabler

#4077 Fix the assignment grouping migration to include the indexes correctly
  lms/migrations/versions/1e146996cca6_add_assignment_grouping.py
Labels: Bug, Technical enabler

#4079 Update handling of slashes in JSTOR API endpoint paths
  lms/services/jstor.py
  tests/unit/lms/services/jstor_test.py
Labels: JSTOR

#4076 Make JSTOR article thumbnail show first page instead of last page.
  lms/services/jstor.py
  tests/unit/lms/services/jstor_test.py
Labels: JSTOR

#4090 Remove `canvas_api_custom_domain` from the launch context
  lms/resources/_js_config/file_picker_config.py
  lms/resources/lti_launch.py
  lms/validation/_lti_launch_params.py
  tests/unit/lms/resources/_js_config/file_picker_config_test.py
  tests/unit/lms/resources/lti_launch_test.py
Labels: Tech debt

#4115 Remove reports
  docs/configuration.md
  gulpfile.mjs
  lms/assets.ini
  lms/authentication/password_hash.py
  lms/config.py
  lms/routes.py
  lms/scripts/get_password_hash.py
  lms/security.py
  lms/static/styles/README.md
  lms/static/styles/reports.css
  lms/templates/login.html.jinja2
  lms/templates/reports/application_report.html.jinja2
  lms/views/authentication.py
  lms/views/lti/basic_launch.py
  lms/views/reports.py
  tests/conftest.py
  tests/functional/conftest.py
  tests/functional/views/reports_test.py
  tests/unit/lms/authentication/__init__.py
  tests/unit/lms/authentication/password_hash_test.py
  tests/unit/lms/security_test.py
  tests/unit/lms/views/authentication_test.py
  tests/unit/lms/views/reports_test.py
  tox.ini
Labels: Tech debt

#4124 Show error in JSTOR article picker if item is a collection
  lms/static/scripts/frontend_apps/components/JSTORPicker.js
  lms/static/scripts/frontend_apps/components/test/JSTORPicker-test.js
  lms/views/api/jstor.py
  tests/unit/lms/views/api/jstor_test.py
Labels: Frontend

#4098 Improve extraction of titles from JSTOR API responses
  lms/services/jstor.py
  tests/unit/lms/services/jstor_test.py
Labels: Added to sprint

#4146 Store group membership data for courses
  lms/views/lti/basic_launch.py
  tests/unit/lms/views/lti/basic_launch_test.py
Labels: Tech debt
