Repository hypothesis/lms, pull requests merged in 2022-05, with the labels that each got.

#3928 Add support for JSON-RPC 2.0 Notification requests
  lms/static/scripts/postmessage_json_rpc/client.js
  lms/static/scripts/postmessage_json_rpc/index.js
  lms/static/scripts/postmessage_json_rpc/server.js
  lms/static/scripts/postmessage_json_rpc/test/client-test.js
  lms/static/scripts/postmessage_json_rpc/test/server-test.js
Labels: Frontend

#3917 Deep Linking in LTI1.3 launches
  lms/models/lti_params.py
  lms/resources/_js_config/__init__.py
  lms/routes.py
  lms/services/ltia_http.py
  lms/static/scripts/frontend_apps/components/FilePickerApp.js
  lms/static/scripts/frontend_apps/components/test/FilePickerApp-test.js
  lms/static/scripts/frontend_apps/config.js
  lms/validation/_lti_launch_params.py
  lms/views/lti/deep_linking.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/validation/_lti_launch_params_test.py
  tests/unit/lms/views/lti/deep_linking_test.py
Labels: enhancement

#3956 Canvas: Only submit for grading if annotation is shared
  lms/static/scripts/frontend_apps/components/BasicLTILaunchApp.js
  lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js
  lms/static/scripts/frontend_apps/services/client-rpc.js
  lms/static/scripts/frontend_apps/services/test/client-rpc-test.js
Labels: Frontend

#3973 Remove vitalsource_anon_launch feature flag
  lms/resources/_js_config/__init__.py
  tests/unit/lms/resources/_js_config/__init___test.py
Labels: VitalSource

#3975 Remove code to support LTI-authenticated LMS launches
  docs/configuration.md
  lms/config/__init__.py
  lms/services/vitalsource/client.py
  tests/conftest.py
  tests/unit/lms/services/vitalsource/client_test.py
  tox.ini
Labels: VitalSource

#4010 Remove `h_group` property from the context
  lms/resources/_js_config/__init__.py
  lms/resources/lti_launch.py
  lms/views/basic_lti_launch.py
  lms/views/lti/deep_linking.py
  tests/unit/lms/resources/_js_config/__init___test.py
  tests/unit/lms/resources/lti_launch_test.py
  tests/unit/lms/views/basic_lti_launch_test.py
  tests/unit/lms/views/lti/deep_linking_test.py
Labels: Tech debt
