Repository hypothesis/lms, pull requests merged in 2023-01, with the labels that each got.

#4874 Fix crashes in the organization hierarchy view caused by null names
  lms/templates/admin/organization.html.jinja2
  lms/views/admin/organization.py
  tests/unit/lms/views/admin/organization_test.py
Labels: Bug

#4879 Adjust some LMSFilePicker tests to await on components rendering when appropriate
  lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
Labels: Frontend

#4887 Move settings defaults for application instances into the service
  lms/services/application_instance.py
  lms/views/application_instances.py
  tests/unit/lms/services/application_instance_test.py
  tests/unit/lms/views/application_instance_test.py
Labels: Tech debt

#4853 Add support to load nested children in the file picker if we already have them
  lms/static/scripts/frontend_apps/api-types.js
  lms/static/scripts/frontend_apps/components/LMSFilePicker.tsx
  lms/static/scripts/frontend_apps/components/test/LMSFilePicker-test.js
Labels: Frontend

#4930 Fix the definition of billable to include at least one annotation in the group
  lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organization_activity/01_create_view.sql
Labels: Bug

#4914 DB migration to add name to the application instance
  lms/migrations/versions/53f9ad3b93a4_add_a_name_to_application_instances.py
Labels: Technical enabler

#4876 Remove public sign-up page
  lms/templates/application_instances/create_application_instance.html.jinja2
  lms/templates/application_instances/new_application_instance.html.jinja2
  lms/views/application_instances.py
  lms/views/index.py
  tests/unit/lms/views/application_instance_test.py
Labels: Tech debt

#4888 Redirect users who visit us directly to help pages
  lms/routes.py
  lms/views/index.py
  tests/functional/ui/__init__.py
  tests/functional/ui/landing_page_test.py
  tests/unit/lms/views/index_test.py
Labels: enhancement

#4944 Add some warning notes in locations related to users about report implications
  lms/services/lti_h.py
  lms/services/user.py
Labels: documentation

#4891 Tidy up the comment formatting in the application instance model
  lms/models/application_instance.py
Labels: Tech debt
