Repository hypothesis/lms, pull requests merged in 2023-03, with the labels that each got.

#5124 Remove unused CSS, simplify entrypoints and update README
  lms/static/scripts/frontend_apps/components/ErrorDialogApp.tsx
  lms/static/scripts/frontend_apps/components/LaunchErrorDialog.tsx
  lms/static/scripts/frontend_apps/components/OAuth2RedirectErrorApp.tsx
  lms/static/styles/README.md
  lms/static/styles/_components.scss
  lms/static/styles/_utilities.scss
  lms/static/styles/components/_shared.scss
  lms/static/styles/frontend_apps.scss
  lms/static/styles/ui-playground.scss
Labels: Frontend

#5126 Remove unused legacy icons
  lms/static/scripts/bootstrap.js
  lms/static/scripts/frontend_apps/icons.js
  lms/static/scripts/frontend_apps/index.tsx
  lms/static/scripts/ui-playground/index.js
Labels: Frontend

#5132 Add a method for calling the `h` bulk annotation end-point
  lms/resources/_js_config/__init__.py
  lms/services/__init__.py
  lms/services/h_api.py
  lms/services/lti_h.py
  tests/unit/lms/services/__init___test.py
  tests/unit/lms/services/h_api_test.py
  tests/unit/services.py
Labels: Technical enabler

#5152 Convert remaining Preact components to TypeScript
  lms/static/scripts/frontend_apps/components/ContentFrame.tsx
  lms/static/scripts/frontend_apps/components/FilePickerFormFields.tsx
  lms/static/scripts/frontend_apps/components/ValidationMessage.tsx
Labels: Frontend

#5137 Misc Application Instance refactors
  lms/services/application_instance.py
Labels: Tech debt

#5189 Update pattern-library docs for `LaunchErrorDialog`
  lms/static/scripts/ui-playground/components/ErrorComponents.tsx
Labels: Frontend

#5211 Add sketches of edit-assignment workflow starting point to pattern library
  lms/static/scripts/ui-playground/components/EditAssignment.tsx
  lms/static/scripts/ui-playground/index.js
Labels: Frontend

#5242 Use the logged in users email to set the default in the admin pages
  lms/templates/admin/email.html.jinja2
Labels: enhancement
