Repository hypothesis/lms, pull requests merged in 2023-06, with the labels that each got.

#5467 Add a slightly sanitized view of assignments
  lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/02_entities/04_assignments/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/03_cross_reference/05_organization_assignments/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/03_cross_reference/05_organization_assignments/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
  lms/data_tasks/report/refresh/01_entities_refresh.sql
  lms/data_tasks/report/refresh/02_cross_reference_refresh.sql
Labels: Technical enabler

#5494 Add multiple versions of group annotation types
  lms/data_tasks/report/create_from_scratch/00_schema/03_create_fdw_schema.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/01_group_activity/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/02_group_bubbled_activity/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/02_group_bubbled_activity/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/03_group_bubbled_counts/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/04_group_type_counts/01_create_view.jinja2.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/04_group_type_counts/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/05_group_bubbled_type_counts/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/01_groups/05_group_bubbled_type_counts/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organizations/01_organization_activity/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organizations/01_organization_activity/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organizations/02_organization_annotation_types/01_create_view.sql
  lms/data_tasks/report/create_from_scratch/04_activity_counts/03_organizations/02_organization_annotation_types/02_initial_fill.sql
  lms/data_tasks/report/create_from_scratch/99_grant_permissions/01_grant_schema.jinja2.sql
  lms/data_tasks/report/refresh/03_activity_counts_refresh.sql
Labels: Technical enabler

#5500 Use YouTube video title as assignment description
  lms/static/scripts/frontend_apps/components/ContentSelector.tsx
  lms/static/scripts/frontend_apps/components/FilePickerApp.tsx
  lms/static/scripts/frontend_apps/components/YouTubePicker.tsx
  lms/static/scripts/frontend_apps/components/test/ContentSelector-test.js
  lms/static/scripts/frontend_apps/components/test/YouTubePicker-test.js
Labels: Project: Video Annotations

#5503 Do not allow YouTube video URLs when using the URLPicker
  lms/static/scripts/frontend_apps/components/ContentSelector.tsx
  lms/static/scripts/frontend_apps/components/URLPicker.tsx
  lms/static/scripts/frontend_apps/components/test/URLPicker-test.js
Labels: Project: Video Annotations

#5502 Add dates to the user table in reporting
  lms/data_tasks/report/create_from_scratch/05_entities_decorated/01_users/01_create_view.jinja2.sql
Labels: Technical enabler

#5518 Fix the bubbling counts to be arranged by parent, not child
  lms/data_tasks/report/create_from_scratch/05_activity_counts/02_groups/02_group_bubbled_annotation_counts/01_create_view.jinja2.sql
Labels: bug
